name: Python unit tests
run-name: ${{ github.actor }} unit test run
on: [push]
jobs:
  python-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - run: python3 mqtt_tests.py
      - run: python3 mqtt_message_tests.py
